[tool.poetry]
name = "{{cookiecutter.project_name}}"
version = "0.0.1"
description = "{{cookiecutter.project_description}}"
authors = ["{{cookiecutter.author_name}} <{{cookiecutter.email}}>"]
readme = "README.md"
classifiers = ["License :: OSI Approved :: MIT License",
               "Programming Language :: Python :: 3.8",
               "Programming Language :: Python :: 3.9"]

[tool.poetry.dependencies]
python = "{{cookiecutter.compatible_python_versions}}"
hydra-core = "^1.1.1"
pdoc3 = "^0.10.0"
jupyterlab = "^3.4.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pre-commit = "^2.17.0"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ['--verbose',
           '--durations=10',
           '--color=yes',
           '-s',
           '-vv',
           '--doctest-modules']
xfail_strict = true
filterwarnings = ["ignore"]
log_cli_level = "info"
testpaths = ["tests"]

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
	\.git
| \.hg
| \.mypy_cache
| \.tox
| \.venv
| _build
| buck-out
| build
)/
'''

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
