{{'[tool.poetry]' if cookiecutter.dependency_manager != 'pip' else '[project]'}}
name = "{{cookiecutter.project_name}}"
description = "{{cookiecutter.project_description}}"
version = "0.0.0"{{'\nauthors = [\n    "' if cookiecutter.dependency_manager != 'pip'}}{{cookiecutter.author_name if cookiecutter.dependency_manager != 'pip'}}{{' <' if cookiecutter.dependency_manager != 'pip'}}{{cookiecutter.email if cookiecutter.dependency_manager != 'pip'}}{{'>",\n]' if cookiecutter.dependency_manager != 'pip'}}
readme = "README.md"{{'\nlicense = ' if cookiecutter.dependency_manager != 'pip'}}{{'"MIT"' if cookiecutter.open_source == "y" and cookiecutter.dependency_manager != 'pip'}}{{'"Proprietary"' if cookiecutter.open_source != "y" and cookiecutter.dependency_manager != 'pip'}}{{'\n\n[tool.poetry.dependencies]' if cookiecutter.dependency_manager != 'pip'}}
{{'python' if cookiecutter.dependency_manager != 'pip' else 'requires-python'}} = ">={{ cookiecutter.python_version }},<3.13"{{'' if cookiecutter.dependency_manager != 'pip' else '\ndependencies = ['}}
{{'hydra-core = "^1.3.2"' if cookiecutter.dependency_manager != 'pip' else ' "hydra-core==1.3.2",\n]'}}{{'' if cookiecutter.dependency_manager != 'pip' else '\n[[project.authors]]\nname = "'}}{{cookiecutter.author_name if cookiecutter.dependency_manager == 'pip'}}{{'"\nemail = "' if cookiecutter.dependency_manager == 'pip'}}{{cookiecutter.email if cookiecutter.dependency_manager == 'pip'}}{{'"' if cookiecutter.dependency_manager == 'pip'}}

[build-system]
requires = [
    "{{'poetry-core>=1.0.0' if cookiecutter.dependency_manager != 'pip' else 'setuptools>=68.0.0'}}"
]
build-backend = "{{'poetry.core.masonry.api' if cookiecutter.dependency_manager != 'pip' else 'setuptools.build_meta'}}"
{{'\n[project.license]\nfile = "LICENSE"\n' if cookiecutter.dependency_manager == 'pip'}}
{{'[tool.poetry.group.dev.dependencies]' if cookiecutter.dependency_manager != 'pip' else '[project.optional-dependencies]\ndev = ['}}
{{'pytest = "^7.4.3"' if cookiecutter.dependency_manager != 'pip' else '    "pytest==7.4.3",'}}
{{'pytest-xdist = "^3.3.1"' if cookiecutter.dependency_manager != 'pip' else '    "pytest-xdist==3.3.1",'}}
{{'pytest-cov = "^4.1.0"' if cookiecutter.dependency_manager != 'pip' else '    "pytest-cov==4.1.0",'}}
{{'pre-commit = "^3.5.0"' if cookiecutter.dependency_manager != 'pip' else '    "pre-commit==3.5.0",'}}
{{'pdoc = "^14.1.0"' if cookiecutter.dependency_manager != 'pip' else '    "pdoc==14.1.0",'}}
{{'' if cookiecutter.dependency_manager != 'pip' else '    "coverage[toml]==5.5",'}}{{'readme-coverage-badger = ">=0.1.2,<1.0.0"' if cookiecutter.dependency_manager != 'pip' else '\n    "readme-coverage-badger==0.1.2",'}}
{{'click = "^8.1.7"' if cookiecutter.dependency_manager != 'pip' else '    "click==8.1.7",\n]'}}
{{'\n[[tool.poetry.source]]\nname = "pypi"\n\n' if cookiecutter.dependency_manager != 'pip'}}
[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
	\.git
| \.hg
| \.mypy_cache
| \.tox
| \.venv
| _build
| buck-out
| build
)/
'''

[tool.ruff]
target-version = "{{'py312' if cookiecutter.python_version == '3.12'}}{{'py311' if cookiecutter.python_version == '3.11'}}{{'py310' if cookiecutter.python_version == '3.10'}}{{'py39' if cookiecutter.python_version == '3.9'}}{{'py38' if cookiecutter.python_version == '3.8'}}{{'py37' if cookiecutter.python_version == '3.7'}}"
extend-select = [
    "I",
]

[tool.ruff.extend-per-file-ignores]
"__init__.py" = [
    "F401",
]
"src/scripts/your_script.py" = [
    "I",
]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = [
    '--verbose',
    '--durations=10',
    '--color=yes',
    '-s',
    '-vv',
    '--doctest-modules',
    '--cov=src/{{cookiecutter.project_name}}',
    '-n 2',
]
xfail_strict = true
filterwarnings = [
    "error",
    "ignore::UserWarning",
    "ignore::DeprecationWarning",
    "ignore::ImportWarning",
]
log_cli_level = "info"
testpaths = [
    "tests",
    "src/{{cookiecutter.project_name}}",
]
